# hrm app includes two docker services
# 1. node js + nest js REST API
# 2. mysql database server

services:
  myhrm-app:
    image: node:20-alpine
    container_name: myhrm-app-v1
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    command: ./start.sh
    depends_on:
      - mysql

  cloudwatch-agent:
    image: amazon/cloudwatch-agent:latest
    container_name: cloudwatch-agent-v1
    env_file:
      - .env
    volumes:
      - ./cloudwatch-config.json:/etc/cloudwatch-agent/config.json:ro
      - /logs:/app/logs
    environment:
      - CW_CONFIG_FILE=/etc/cloudwatch-agent/config.json
    command: ["/opt/aws/amazon-cloudwatch-agent/bin/start-amazon-cloudwatch-agent"]

  mysql:
    image: mysql:8.0
    container_name: mysql-db-myhrm-app-v1
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_data:
    driver: local
