# putting postgres container into overrides
# to be used only in the dev environment.

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db-myhrm-app-v1
    env_file:
      - .env
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=${PRIMARY_DATABASE_PASSWORD}
      - POSTGRES_USER=${PRIMARY_DATABASE_USERNAME}
      - POSTGRES_DB=${PRIMARY_DATABASE}
    command: postgres -c timezone=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  myhrm-app:
    environment:
      DATABASE_URL: postgresql://${PRIMARY_DATABASE_USERNAME}:${PRIMARY_DATABASE_PASSWORD}@postgres-db-myhrm-app-v1:5432/${PRIMARY_DATABASE}
    depends_on:
      - postgres

  worker:
    environment:
      DATABASE_URL: postgresql://${PRIMARY_DATABASE_USERNAME}:${PRIMARY_DATABASE_PASSWORD}@postgres-db-myhrm-app-v1:5432/${PRIMARY_DATABASE}
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
